### ISSUE TITLE
File naming scheme for Drive and Journal

### ISSUE THREAD

**Issue by louisbertrand** [Safecast/bGeigieZen#37]
The file names should encode essential information to show status at a glance. The Core and Core2 API permit writing file names longer than the old DOS 8.3 constraint, and also create directories and subdirectories.
The information for Drive:
date-time started (first record written)
has it been submitted?
** what else? **

**Comment by louisbertrand** [comment]
Existing bGeigie Nano file naming is
UUUUMMDD.LOG
where UUUU stands for the 4-digit device ID, and MMDD is 2-digit month and 2-digit day of the month. The year cannot be encoded in the file name, so logging on the same month/day in multiple years will append to the same file. A workaround is to mount the uSD card on a PC and archive the file after it has been submitted to the API. Manually move the latest files to a separate folder for each year.

**Comment by louisbertrand** [comment]
Open questions:
If the file name must include date and time (e.g. ISO standard YYYY-MM-DDTHH:MM:SSZ), can a journal file be opened and named before getting a GPS fix? 
Create a separate folder for each year?
What status needs to be encoded? New, Submitted, what else?

**Comment by robouden** [comment]
> Existing bGeigie Nano file naming is UUUUMMDD.LOG where UUUU stands for the 4-digit device ID, and MMDD is 2-digit month and 2-digit day of the month. The year cannot be encoded in the file name, so logging on the same month/day in multiple years will append to the same file. A workaround is to mount the uSD card on a PC and archive the file after it has been submitted to the API. Manually move the latest files to a separate folder for each year.

The way that Robin worded around that is by creating year folders in the Zen..
