### ISSUE TITLE
Can date-time be known before GPS ready?

### ISSUE THREAD

**Issue by louisbertrand** [Safecast/bGeigieZen#39]
It would be very convenient to begin journalling as soon as the system is started, but without date-time, it's hard to write reliable information. 
Is there a real-time clock on the M5Stack Core and Core2?
Can the millis() be relied upon if the system sleeps? Is there an indication that a boot has occurred (cold boot, warm boot)?

**Comment by louisbertrand** [comment]
The Core2 includes a RTC (NXP BM8563) with Arduino driver https://github.com/tanakamasayuki/I2C_BM8563
Unfortunately, the original Core does not.
The RTC on the Core2 does not appear to be initialized when shipped from the factory. 
For example, with a simple read without first setting the date-time, I get 2000//00/16 07:25:42. Running the example again, the minutes and seconds advance as expected, therefore it seems that I am reading the IC correctly.
See the first few commits in  https://github.com/louisbertrand/core2_rtc_test

**Comment by robouden** [comment]
I checked the RTC is on the main board, not on the extension board:

From the M5Stack docs: 
"There is a small expansion board on the back of the base with a 6-axis IMU sensor and microphone. There is a small expansion board on the back of the base with a 6-axis IMU sensor and microphone. "

**Comment by louisbertrand** [comment]
For journalling purposes only, I propose to add an item in local storage for "last known date-time", to be updated at the same time as last_longitude and last_latitude. This last known date-time can be used as the file name for a new journal file on a cold start (no GNSS time known, and no realtime clock IC available.
The last known date-time can be kept in class LocalStorage (local_storage.h).
When the system boots, the journal file is created with a file name based on the last known date-time:
YYYY-MM-DD_HH-MM-SS_TEMP_JRNLTXT
Entries are timestamped with the millis() value.
When the correct time becomes available (GNSS), the journal file should be renamed. The renaming should be noted in the journal file so that older entries can be accurately back-dated based the milliseconds timestamps, relative to when the file was renamed.
The last known time is strictly for internal purposes; it would not be visible to the end user or logged to the map database.

**Comment by BeakeS** [comment]
How can I purchase one of these kits?  The website store just hangs when I
try to checkout.

I could help with code development if I had the hardware.

Michael Beakes

**Comment by louisbertrand** [comment]
Hi @BeakeS, the kits are still under development, with only a few prototypes available. Until I got mine, I just used the individual components on breadboards (M5Stack Core and Core2, BN-880 GPS). Without a GM tube, I just used an Arduino to provide pulses.
If you'd like to follow up, the best contact person is lead developer @robouden (Rob Oudendijk).

**Comment by robouden** [comment]
@BeakeS

If you want, you can put in a custom order. Currently, we are just taken in orders. Not selling yet. Production is a work in progress. If you want to help with software development, please join our weekly meeting at:

Join Zoom Meeting
[https://us04web.zoom.us/j/3104600384?pwd=M2tZUGNWQll6aTJEMnByN1YxWUxrdz09](https://www.google.com/url?q=https://us04web.zoom.us/j/3104600384?pwd%3DM2tZUGNWQll6aTJEMnByN1YxWUxrdz09&sa=D&source=calendar&usd=2&usg=AOvVaw0VgS3AhOIiQhz7jdKR2oJE)

Meeting ID: 310 460 0384
Passcode: 9ZjWD6

Schedule is below:
![image](https://github.com/Safecast/bGeigieZen/assets/1387190/74d7bd4b-f457-4abe-972e-8f788416fd1a)

**Comment by robouden** [comment]
> I checked the RTC is on the main board, not on the extension board:
> 
> From the M5Stack docs: "There is a small expansion board on the back of the base with a 6-axis IMU sensor and microphone. There is a small expansion board on the back of the base with a 6-axis IMU sensor and microphone. "

Great find. Did you check if it works?
!!!!!

**Comment by louisbertrand** [comment]
Yes, the RTC works well. There is a "not initialized" bit that we can query, but it starts keeping time immediately even if the starting point is random after initial power up.

**Comment by robouden** [comment]
And if the power is off, still on boot it has the correct time?

Regards,
Rob

**Comment by louisbertrand** [comment]
Yup, battery backed up, but I need to confirm. I've had it powered off for a while, good opportunity to check.

**Comment by robouden** [comment]
Seems you figured it out already

**Comment by louisbertrand** [comment]
Yes, but also confirm on the actual prototype, with the external battery and charger, just to make sure it wasn't using the Core battery.

**Comment by robouden** [comment]
BeakeS,

If you send us your email, I can invite you for the Slack channel of bGeigieZen for software and hardware discussions.

Regards,
Rob Oudendijk

**Comment by BeakeS** [comment]
Rob,

Thanks for the reply.
My email is ***@***.***

Michael

**Comment by robouden** [comment]
BeakeS,  

Interesting email address.
Noticed you have 0 repos on GitHub, are you new to GitHub?

 

Regards,
Rob Oudendijk

**Comment by BeakeS** [comment]
Not new to github but not an expert either.  Had a different account/email
when I was a mentor for high school robotics teams.

Since I retired in 2021, I've been working on a lot of
microcontroller-based projects - mostly networked home sensor/control for
optimizing multi-zone hvac, water well monitoring, and security.  My son
has been bugging me for some time to push all my code off my linux box and
onto github.  No time like the present.

Michael

**Comment by robouden** [comment]
BeakeS,

Thanks for the reply.
Better keep all your code on GitHub if you work in a team. So easy to roll
back, branch etc.

You want me to add you to the Safecast Slack channel?

Regards,
Rob Oudendijk

**Comment by BeakeS** [comment]
Yes, please do.

Thanks,
Michael

**Comment by robouden** [comment]
BeakeS,

Still need your email address.

Rob

**Comment by BeakeS** [comment]
***@***.***

(I sent it when you first asked but changed the subject line.)

Thanks.

**Comment by robouden** [comment]
Can you resend it to my email address below, or maybe better with Signal or
Keybase?



Regards,
Rob Oudendijk
https://yr-design.biz <http://yr-design.biz/>   https://oudendijk.biz
<http://oudendijk.biz/>  https://about.me/robouden
<http://about.me/robouden>tel +81 80-22605966  Skype: robouden  Facebook:
robouden <http://on.fb.me/QeKw2P> linkedin:robouden
<https://www.linkedin.com/in/roboudendijk>
