### ISSUE TITLE
On satellites display have different color for different satellites constellations.

### ISSUE THREAD

**Issue by robouden** [Safecast/bGeigieZen#67]
GPS	
GLONASS	
Galileo	
BeiDou	
QZSS	
IRNSS/NavIC

**Comment by BeakeS** [comment]
Is this for the Zen satellite display?
The first letter indicates the gnss, G=GPS, S=SBAS, E=Galileo, B=BeiDou, Q=QZSS, R=GLONASS, I=IRNSS, ...
The sat color color and ring colors are already used for other indicators.  Sat color, blue/red,  indicates usedfornav/notusedfornav and the ring color indicates signal strength.
