### ISSUE TITLE
Add high current charging for Core 2

### ISSUE THREAD

**Issue by robouden** [Safecast/bGeigieZen#71]
Use M5.Axp.SetCHGCurrent(AXP192::kCHG_1320mA); for 1320mA charging on the USB-C connector.

**Comment by louisbertrand** [comment]
Is fast charge necessary?
Realistically, how many pre-production Zens have AXP192? New CORE2 modules all have AXP2101.

**Comment by robouden** [comment]
Fast charge is a requirement.!!!
But If we can not fast charge,  we can always exchange the empty battery
easy with a charged one.
